apiVersion: v2
name: insight
description: Helm Chart for deploying to Kubernetes of service insight for state-manager
  as a part of reconcile-kit 
type: application
version: 0.1.0
appVersion: "0.0.10"
