
name: Release chart

on:
  push:
    branches:
      - main

env:
  HELM_VERSION: 3.18.6
  YQ_VERSION: 4.44.2

jobs:
  package-helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
  
      - name: Install tools
        uses: yokawasa/action-setup-kube-tools@v0.11.1
        with:
          setup-tools: |
            helmv3
            yq
          helm: "${{ env.HELM_VERSION }}"
          yq: "${{ env.YQ_VERSION }}"
      
      - name: Add dependencies
        run: |
          yq -M eval '.repositories[] | (.name + " " + .url)' .github/ci/helm-repos.yaml | xargs -L 1 helm repo add
          make helm-repo-update
      
      - name: Release
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN_GENERAL }}"
        with:
          config: .github/ci/cr.yaml